#!/bin/bash
if [[ $# -ne 2 ]]; then
    echo "USAGE: getThreadDumps <seconds to wait> <output file>"
    exit -1
fi

SERVER_PID=`ps -eaf | grep jenkins | awk -F' ' '{print $2}'`

if [[ -z "$SERVER_PID" ]]; then
    echo "could not find surefire process"
    exit -1
fi

echo Surefire PIDs $SERVER_PID
SLEEP_TIME=$1
while [ 0 -eq 0 ];
do
    for pid in $SERVER_PID; do
        echo Getting thread dump for PID $pid
        kill -3 $pid >> $2
#        jstack -J-Xmx50m $pid >> $2
    done
    echo Sleeping $1 seconds
    sleep $1
done
